# This is a basic workflow to help you get started with Actions

name: action

on:
  push:
    branches: [ github_actions, master ]
  pull_request:
    branches: [ github_actions, master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: ls -la

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
